import { Subject } from 'rxjs';
import type { GroupChatClosedEvent } from '../events/GroupChatClosedEvent';
import type { NewObjectEvent } from '../events/NewObjectEvent';
import type { ObjectUpdatedEvent } from '../events/ObjectUpdatedEvent';
import type { ObjectKilledEvent } from '../events/ObjectKilledEvent';
import type { SelectedObjectEvent } from '../events/SelectedObjectEvent';
import type { ChatEvent } from '../events/ChatEvent';
import type { InstantMessageEvent } from '../events/InstantMessageEvent';
import type { GroupInviteEvent } from '../events/GroupInviteEvent';
import type { FriendRequestEvent } from '../events/FriendRequestEvent';
import type { InventoryOfferedEvent } from '../events/InventoryOfferedEvent';
import type { LureEvent } from '../events/LureEvent';
import type { TeleportEvent } from '../events/TeleportEvent';
import type { DisconnectEvent } from '../events/DisconnectEvent';
import type { GroupChatEvent } from '../events/GroupChatEvent';
import type { GroupNoticeEvent } from '../events/GroupNoticeEvent';
import type { GroupChatSessionJoinEvent } from '../events/GroupChatSessionJoinEvent';
import type { GroupChatSessionAgentListEvent } from '../events/GroupChatSessionAgentListEvent';
import type { FriendResponseEvent } from '../events/FriendResponseEvent';
import type { ScriptDialogEvent } from '../events/ScriptDialogEvent';
import type { EventQueueStateChangeEvent } from '../events/EventQueueStateChangeEvent';
import type { FriendOnlineEvent } from '../events/FriendOnlineEvent';
import type { FriendRightsEvent } from '../events/FriendRightsEvent';
import type { FriendRemovedEvent } from '../events/FriendRemovedEvent';
import type { ObjectPhysicsDataEvent } from '../events/ObjectPhysicsDataEvent';
import type { ParcelPropertiesEvent } from '../events/ParcelPropertiesEvent';
import type { ObjectResolvedEvent } from '../events/ObjectResolvedEvent';
import type { Avatar } from './public/Avatar';
import type { BulkUpdateInventoryEvent } from '../events/BulkUpdateInventoryEvent';
import type { InventoryResponseEvent } from '../events/InventoryResponseEvent';
import type { LandStatsEvent } from '../events/LandStatsEvent';
import type { SimStatsEvent } from '../events/SimStatsEvent';
import type { BalanceUpdatedEvent } from '../events/BalanceUpdatedEvent';
import { FilterResponse } from '../enums/FilterResponse';
import type { UUID } from './UUID';
export declare class ClientEvents {
    onNearbyChat: Subject<ChatEvent>;
    onInstantMessage: Subject<InstantMessageEvent>;
    onGroupInvite: Subject<GroupInviteEvent>;
    onFriendRequest: Subject<FriendRequestEvent>;
    onInventoryOffered: Subject<InventoryOfferedEvent>;
    onLure: Subject<LureEvent>;
    onTeleportEvent: Subject<TeleportEvent>;
    onDisconnected: Subject<DisconnectEvent>;
    onCircuitLatency: Subject<number>;
    onGroupChat: Subject<GroupChatEvent>;
    onGroupChatClosed: Subject<GroupChatClosedEvent>;
    onGroupNotice: Subject<GroupNoticeEvent>;
    onGroupChatSessionJoin: Subject<GroupChatSessionJoinEvent>;
    onGroupChatAgentListUpdate: Subject<GroupChatSessionAgentListEvent>;
    onFriendResponse: Subject<FriendResponseEvent>;
    onInventoryResponse: Subject<InventoryResponseEvent>;
    onScriptDialog: Subject<ScriptDialogEvent>;
    onEventQueueStateChange: Subject<EventQueueStateChangeEvent>;
    onFriendOnline: Subject<FriendOnlineEvent>;
    onFriendRights: Subject<FriendRightsEvent>;
    onFriendRemoved: Subject<FriendRemovedEvent>;
    onPhysicsDataEvent: Subject<ObjectPhysicsDataEvent>;
    onParcelPropertiesEvent: Subject<ParcelPropertiesEvent>;
    onNewObjectEvent: Subject<NewObjectEvent>;
    onObjectUpdatedEvent: Subject<ObjectUpdatedEvent>;
    onObjectUpdatedTerseEvent: Subject<ObjectUpdatedEvent>;
    onObjectKilledEvent: Subject<ObjectKilledEvent>;
    onSelectedObjectEvent: Subject<SelectedObjectEvent>;
    onObjectResolvedEvent: Subject<ObjectResolvedEvent>;
    onAvatarEnteredRegion: Subject<Avatar>;
    onRegionTimeDilation: Subject<number>;
    onBulkUpdateInventoryEvent: Subject<BulkUpdateInventoryEvent>;
    onLandStatReplyEvent: Subject<LandStatsEvent>;
    onSimStats: Subject<SimStatsEvent>;
    onBalanceUpdated: Subject<BalanceUpdatedEvent>;
    onScriptRunningReply: Subject<{
        ItemID: UUID;
        Mono: boolean;
        ObjectID: UUID;
        Running: boolean;
    }>;
    waitForEvent<T>(subj: Subject<T>, messageFilter?: (message: T) => FilterResponse, timeout?: number): Promise<T>;
}
//# sourceMappingURL=ClientEvents.d.ts.map