import { AssetType } from '../enums/AssetType';
import type { AttachmentPoint } from '../enums/AttachmentPoint';
import type { InventoryItemFlags } from '../enums/InventoryItemFlags';
import { InventoryType } from '../enums/InventoryType';
import { PermissionMask } from '../enums/PermissionMask';
import type { Agent } from './Agent';
import { InventoryFolder } from './InventoryFolder';
import { UUID } from './UUID';
import { Vector3 } from './Vector3';
import { GameObject } from './public/GameObject';
export declare class InventoryItem {
    private readonly container?;
    private readonly agent?;
    assetID: UUID;
    inventoryType: InventoryType;
    name: string;
    metadata: string;
    salePrice: number;
    saleType: number;
    created: Date;
    parentID: UUID;
    flags: InventoryItemFlags;
    itemID: UUID;
    oldItemID?: UUID;
    parentPartID?: UUID;
    permsGranter?: UUID;
    description: string;
    type: AssetType;
    callbackID: number;
    scriptRunning?: boolean;
    scriptMono?: boolean;
    permissions: {
        baseMask: PermissionMask;
        groupMask: PermissionMask;
        nextOwnerMask: PermissionMask;
        ownerMask: PermissionMask;
        everyoneMask: PermissionMask;
        lastOwner: UUID;
        owner: UUID;
        creator: UUID;
        group: UUID;
        groupOwned?: boolean;
    };
    constructor(container?: (GameObject | InventoryFolder) | undefined, agent?: Agent | undefined);
    static fromEmbeddedAsset(lineObj: {
        lines: string[];
        lineNum: number;
        pos: number;
    }, container?: GameObject | InventoryFolder, agent?: Agent): InventoryItem;
    static fromXML(xml: string): Promise<InventoryItem>;
    toAsset(indent?: string): string;
    getCRC(): number;
    update(): Promise<void>;
    moveToFolder(targetFolder: InventoryFolder): Promise<InventoryItem>;
    delete(): Promise<void>;
    exportXML(): string;
    detachFromAvatar(): Promise<void>;
    attachToAvatar(attachPoint: AttachmentPoint, timeout?: number): Promise<GameObject>;
    rezGroupInWorld(position: Vector3): Promise<GameObject[]>;
    rezInWorld(position: Vector3, objectScale?: Vector3): Promise<GameObject>;
    rename(newName: string): Promise<void>;
    isScriptRunning(): Promise<boolean>;
    copyTo(target: InventoryFolder, name: string): Promise<InventoryItem>;
    updateScript(scriptAsset: Buffer, running?: boolean, target?: 'mono' | 'lsl2'): Promise<UUID>;
    setScriptRunning(running: boolean): Promise<void>;
    private waitForCallbackID;
}
//# sourceMappingURL=InventoryItem.d.ts.map