import { LLSDReal } from "./llsd/LLSDReal";
import { UUID } from './UUID';
import { LLSDMap } from './llsd/LLSDMap';
import type { Vector3 } from './Vector3';
import type { Vector2 } from './Vector2';
import type { Quaternion } from './Quaternion';
import { Vector4 } from './Vector4';
import type { LLSDType } from './llsd/LLSDType';
import { LLSDInteger } from './llsd/LLSDInteger';
interface TermConfigLLSD {
    anisotropy?: LLSDReal;
    constant_term: LLSDReal;
    exp_scale: LLSDReal;
    exp_term: LLSDReal;
    linear_term: LLSDReal;
    width: LLSDReal;
}
export interface HazeConfigLLSD {
    ambient?: LLSDReal[];
    blue_density?: LLSDReal[];
    blue_horizon?: LLSDReal[];
    density_multiplier?: LLSDReal;
    distance_multiplier?: LLSDReal;
    haze_density?: LLSDReal;
    haze_horizon?: LLSDReal;
}
export interface SettingsConfigLLSD {
    asset_id?: UUID;
    flags?: LLSDInteger;
    absorption_config?: TermConfigLLSD[];
    bloom_id?: UUID;
    cloud_color?: LLSDReal[];
    cloud_id?: UUID;
    cloud_pos_density1?: LLSDReal[];
    cloud_pos_density2?: LLSDReal[];
    cloud_scale?: LLSDReal;
    cloud_scroll_rate?: LLSDReal[];
    cloud_shadow?: LLSDReal;
    cloud_variance?: LLSDReal;
    dome_offset?: LLSDReal;
    dome_radius?: LLSDReal;
    droplet_radius?: LLSDReal;
    gamma?: LLSDReal;
    glow?: LLSDReal[];
    halo_id?: UUID;
    ice_level?: LLSDReal;
    legacy_haze?: HazeConfigLLSD;
    max_y?: LLSDReal;
    mie_config?: TermConfigLLSD[];
    moisture_level?: LLSDReal;
    moon_brightness?: LLSDReal;
    moon_id?: UUID;
    moon_rotation?: LLSDReal[];
    moon_scale?: LLSDReal;
    name?: string;
    planet_radius?: LLSDReal;
    rainbow_id?: UUID;
    rayleigh_config?: TermConfigLLSD[];
    sky_bottom_radius?: LLSDReal;
    sky_top_radius?: LLSDReal;
    star_brightness?: LLSDReal;
    sun_arc_radians?: LLSDReal;
    sun_id?: UUID;
    sun_rotation?: LLSDReal[];
    sun_scale?: LLSDReal;
    sunlight_color?: LLSDReal[];
    type?: string;
    frames?: LLSDMap<SettingsConfigLLSD>;
    tracks?: LLSDMap<{
        key_keyframe: LLSDReal;
        key_name: string;
    }>[][];
    blur_multiplier?: LLSDReal;
    fresnel_offset?: LLSDReal;
    fresnel_scale?: LLSDReal;
    normal_map?: UUID;
    normal_scale?: LLSDReal[];
    scale_above?: LLSDReal;
    scale_below?: LLSDReal;
    underwater_fog_mod?: LLSDReal;
    water_fog_color?: LLSDReal[];
    water_fog_density?: LLSDReal;
    wave1_direction?: LLSDReal[];
    wave2_direction?: LLSDReal[];
}
export interface LLSettingsHazeConfig {
    ambient?: Vector3;
    blueDensity?: Vector3;
    blueHorizon?: Vector3;
    densityMultiplier?: number;
    distanceMultiplier?: number;
    hazeDensity?: number;
    hazeHorizon?: number;
}
export interface LLSettingsTermConfig {
    anisotropy?: number;
    constantTerm?: number;
    expScale?: number;
    expTerm?: number;
    linearTerm?: number;
    width?: number;
}
export declare class LLSettings {
    assetID?: UUID;
    flags?: number;
    absorptionConfig?: LLSettingsTermConfig[];
    bloomID?: UUID;
    cloudColor?: Vector3;
    cloudID?: UUID;
    cloudPosDensity1?: Vector3;
    cloudPosDensity2?: Vector3;
    cloudScale?: number;
    cloudScrollRate?: Vector2;
    cloudShadow?: number;
    cloudVariance?: number;
    domeOffset?: number;
    domeRadius?: number;
    dropletRadius?: number;
    gamma?: number;
    glow?: Vector3;
    haloID?: UUID;
    iceLevel?: number;
    legacyHaze?: LLSettingsHazeConfig;
    maxY?: number;
    mieConfig?: LLSettingsTermConfig[];
    moistureLevel?: number;
    moonBrightness?: number;
    moonID?: UUID;
    moonRotation?: Quaternion;
    moonScale?: number;
    name?: string;
    planetRadius?: number;
    rainbowID?: UUID;
    rayleighConfig?: LLSettingsTermConfig[];
    skyBottomRadius?: number;
    skyTopRadius?: number;
    starBrightness?: number;
    sunArcRadians?: number;
    sunID?: UUID;
    sunRotation?: Quaternion;
    sunScale?: number;
    sunlightColor?: Vector4 | Vector3;
    type?: string;
    tracks?: {
        keyKeyframe: number;
        keyName: string;
    }[][];
    frames?: Map<string, LLSettings>;
    blurMultiplier?: number;
    fresnelOffset?: number;
    fresnelScale?: number;
    normalMap?: UUID;
    normalScale?: Vector3;
    scaleAbove?: number;
    scaleBelow?: number;
    underwaterFogMod?: number;
    waterFogColor?: Vector3;
    waterFogDensity?: number;
    wave1Direction?: Vector2;
    wave2Direction?: Vector2;
    constructor(data?: string | LLSDMap<SettingsConfigLLSD>);
    static encodeSettings(settings: LLSettings): LLSDType;
    toAsset(): string;
    private static encodeTermConfig;
    private static encodeHazeConfig;
    private static encodeTracks;
    private static encodeFrames;
    private static validateString;
    private static getRealOrUndef;
    private static validateLLSDReal;
    private static validateUUID;
}
export {};
//# sourceMappingURL=LLSettings.d.ts.map