import type { Circuit } from './Circuit';
import type { ObjectUpdateMessage } from './messages/ObjectUpdate';
import type { ObjectUpdateCachedMessage } from './messages/ObjectUpdateCached';
import type { ObjectUpdateCompressedMessage } from './messages/ObjectUpdateCompressed';
import type { ImprovedTerseObjectUpdateMessage } from './messages/ImprovedTerseObjectUpdate';
import type { Agent } from './Agent';
import { UUID } from './UUID';
import type { ClientEvents } from './ClientEvents';
import type { KillObjectMessage } from './messages/KillObject';
import type { IObjectStore } from './interfaces/IObjectStore';
import { NameValue } from './NameValue';
import { GameObject } from './public/GameObject';
import type { RBush3D } from 'rbush-3d/dist';
import { BotOptionFlags } from '../enums/BotOptionFlags';
import { LLGLTFMaterialOverride } from './LLGLTFMaterialOverride';
import type * as Long from 'long';
import type { GetObjectsOptions } from './commands/RegionCommands';
export declare class ObjectStoreLite implements IObjectStore {
    rtree?: RBush3D;
    protected circuit?: Circuit;
    protected agent: Agent;
    protected objects: Map<number, GameObject>;
    protected objectsByUUID: Map<string, number>;
    protected objectsByParent: Map<number, number[]>;
    protected clientEvents: ClientEvents;
    protected options: BotOptionFlags;
    protected fullStore: boolean;
    protected requestedObjects: Set<number>;
    protected deadObjects: number[];
    protected persist: boolean;
    protected cachedMaterialOverrides: Map<number, Map<number, LLGLTFMaterialOverride>>;
    protected pendingObjectProperties: Map<string, {
        ObjectID: UUID;
        CreatorID: UUID;
        OwnerID: UUID;
        GroupID: UUID;
        CreationDate: Long;
        BaseMask: number;
        OwnerMask: number;
        GroupMask: number;
        EveryoneMask: number;
        NextOwnerMask: number;
        OwnershipCost: number;
        SaleType: number;
        SalePrice: number;
        AggregatePerms: number;
        AggregatePermTextures: number;
        AggregatePermTexturesOwner: number;
        Category: number;
        InventorySerial: number;
        ItemID: UUID;
        FolderID: UUID;
        FromTaskID: UUID;
        LastOwnerID: UUID;
        Name: Buffer;
        Description: Buffer;
        TouchName: Buffer;
        SitName: Buffer;
        TextureID: Buffer;
    }>;
    private readonly physicsSubscription;
    private readonly selectedPrimsWithoutUpdate;
    private selectedChecker?;
    private readonly blacklist;
    private readonly pendingResolves;
    constructor(circuit: Circuit, agent: Agent, clientEvents: ClientEvents, options: BotOptionFlags);
    setPersist(persist: boolean): void;
    deleteObject(objectID: number): void;
    getObjectsByParent(parentID: number): GameObject[];
    parseNameValues(str: string): Map<string, NameValue>;
    shutdown(): void;
    populateChildren(obj: GameObject, _resolve?: boolean): void;
    getAllObjects(options: GetObjectsOptions): GameObject[];
    getNumberOfObjects(): number;
    getObjectsInArea(minX: number, maxX: number, minY: number, maxY: number, minZ: number, maxZ: number): GameObject[];
    getObjectByUUID(fullID: UUID | string): GameObject;
    getObjectByLocalID(localID: number): GameObject;
    insertIntoRtree(obj: GameObject): void;
    pendingResolve(id: number): void;
    private applyObjectProperties;
    protected requestMissingObject(localID: number, attempt?: number): Promise<void>;
    protected objectUpdate(objectUpdate: ObjectUpdateMessage): void;
    protected notifyTerseUpdate(obj: GameObject): void;
    protected notifyObjectUpdate(newObject: boolean, obj: GameObject): void;
    protected objectUpdateCached(objectUpdateCached: ObjectUpdateCachedMessage): void;
    protected objectUpdateCompressed(objectUpdateCompressed: ObjectUpdateCompressedMessage): void;
    protected decodeAttachPoint(state: number): number;
    protected objectUpdateTerse(_objectUpdateTerse: ImprovedTerseObjectUpdateMessage): void;
    protected killObject(killObj: KillObjectMessage): void;
    protected findParent(go: GameObject): GameObject;
}
//# sourceMappingURL=ObjectStoreLite.d.ts.map