import { Vector3 } from './Vector3';
import { UUID } from './UUID';
import { Color4 } from './Color4';
import { ParticleDataFlags } from '../enums/ParticleDataFlags';
import { BlendFunc } from '../enums/BlendFunc';
import { SourcePattern } from '../enums/SourcePattern';
export declare class ParticleSystem {
    startGlow: number;
    endGlow: number;
    blendFuncSource: BlendFunc;
    blendFuncDest: BlendFunc;
    crc: number;
    pattern: SourcePattern;
    maxAge: number;
    startAge: number;
    innerAngle: number;
    outerAngle: number;
    burstRate: number;
    burstRadius: number;
    burstSpeedMin: number;
    burstSpeedMax: number;
    burstPartCount: number;
    angularVelocity: Vector3;
    acceleration: Vector3;
    texture: UUID;
    target: UUID;
    dataFlags: ParticleDataFlags;
    partMaxAge: number;
    startColor: Color4;
    endColor: Color4;
    startScaleX: number;
    startScaleY: number;
    endScaleX: number;
    endScaleY: number;
    flags: number;
    static from(buf: Buffer): ParticleSystem;
    static packFixed(buf: Buffer, pos: number, data: number, signed: boolean, intBits: number, fracBits: number): number;
    static unpackFixed(buf: Buffer, pos: number, signed: boolean, intBits: number, fracBits: number): number;
    static unpackSystem(ps: ParticleSystem, buf: Buffer, pos: number): number;
    static unpackLegacyData(ps: ParticleSystem, buf: Buffer, pos: number): number;
    toBuffer(): Buffer;
    toBase64(): string;
}
//# sourceMappingURL=ParticleSystem.d.ts.map