import type { UUID } from './UUID';
import type { Color4 } from './Color4';
export declare class TextureEntryFace {
    static BUMP_MASK: number;
    static FULLBRIGHT_MASK: number;
    static SHINY_MASK: number;
    static MEDIA_MASK: number;
    static TEX_MAP_MASK: number;
    private _textureID;
    private _rgba;
    private _repeatU;
    private _repeatV;
    private _offsetU;
    private _offsetV;
    private _rotation;
    private _glow;
    private _materialID;
    private _bumpiness;
    private _shininess;
    private _mappingType;
    private _fullBright;
    private _mediaFlags;
    private _material;
    private _media;
    private readonly hasAttribute;
    private readonly defaultTexture;
    constructor(def: TextureEntryFace | null);
    get rgba(): Color4;
    set rgba(value: Color4);
    get repeatU(): number;
    set repeatU(value: number);
    get repeatV(): number;
    set repeatV(value: number);
    get offsetU(): number;
    set offsetU(value: number);
    get offsetV(): number;
    set offsetV(value: number);
    get rotation(): number;
    set rotation(value: number);
    get glow(): number;
    set glow(value: number);
    get textureID(): UUID;
    set textureID(value: UUID);
    get materialID(): UUID;
    set materialID(value: UUID);
    get material(): number;
    set material(material: number);
    get media(): number;
    set media(media: number);
    get mappingType(): number;
    set mappingType(value: number);
    get mediaFlags(): boolean;
    set mediaFlags(value: boolean);
}
//# sourceMappingURL=TextureEntryFace.d.ts.map