export declare enum AttachmentPoint {
    Default = 0,
    Chest = 1,// FS: Chest
    Skull = 2,// FS: Skull
    LeftShoulder = 3,// FS: Left Shoulder
    RightShoulder = 4,// FS: Right Shoulder
    LeftHand = 5,// FS: Left Hand
    RightHand = 6,// FS: Right Hand
    LeftFoot = 7,// FS: Left Foot
    RightFoot = 8,// FS: Right Root
    Spine = 9,// FS: Spine
    Pelvis = 10,// FS: Pelvis
    Mouth = 11,// FS: Mouth
    Chin = 12,// FS: Chin
    LeftEar = 13,// FS: Left Ear
    RightEar = 14,// FS: Right Ear
    LeftEyeball = 15,// FS: Left Eyeball
    RightEyeball = 16,// FS: Right Eyeball
    Nose = 17,// FS: Nose
    RightUpperArm = 18,// FS: R Upper Arm
    RightForearm = 19,// FS: R Forearm
    LeftUpperArm = 20,// FS: L Upper Arm
    LeftForearm = 21,// FS: L Forearm
    RightHip = 22,// FS: Right Hip
    RightUpperLeg = 23,// FS: R Upper Leg
    RightLowerLeg = 24,// FS: R Lower Leg
    LeftHip = 25,// FS: Left Hip
    LeftUpperLeg = 26,// FS: L Upper Leg
    LeftLowerLeg = 27,// FS: L Lower Leg
    Stomach = 28,// FS: Stomach
    LeftPec = 29,// FS: Left Pec
    RightPec = 30,// FS: Right Pec
    HUDCenter2 = 31,// FS: Center 2
    HUDTopRight = 32,// FS: Top Right
    HUDTop = 33,// FS: Top
    HUDTopLeft = 34,// FS: Top Left
    HUDCenter = 35,// FS: Center
    HUDBottomLeft = 36,// FS: Bottom Left
    HUDBottom = 37,// FS: Bottom
    HUDBottomRight = 38,// FS: Bottom Right
    Neck = 39,// FS: Neck
    Root = 40,// FS: Avatar Center
    LefHandRing1 = 41,// FS: Left Ring Finger
    RightHandRing1 = 42,// FS: Right Ring Finger
    TailBase = 43,// FS: Tail Base
    TailTip = 44,// FS: Tail Tip
    LeftWing = 45,// FS: Left Wing
    RightWing = 46,// FS: Right Wing
    FaceJaw = 47,// FS: Jaw
    FaceLeftEar = 48,// FS: Alt Left Ear
    FaceRightEar = 49,// FS: Alt Right Ear
    FaceLeftEye = 50,// FS: Alt Left Eye
    FaceRightEye = 51,// FS: Alt Right Eye
    FaceTongue = 52,// FS: Tongue
    Groin = 53,// FS: Groin
    HindLeftFoot = 54,// FS: Left Hind Foot
    HindRightFoot = 55
}
//# sourceMappingURL=AttachmentPoint.d.ts.map