"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ParcelPropertiesEvent = void 0;
class ParcelPropertiesEvent {
    LocalID;
    RegionDenyAgeUnverified;
    MediaDesc;
    MediaWidth;
    MediaHeight;
    MediaLoop;
    MediaType;
    ObscureMedia;
    ObscureMusic;
    AABBMax;
    AABBMin;
    AnyAVSounds;
    Area;
    AuctionID;
    AuthBuyerID;
    Bitmap;
    Category;
    ClaimDate;
    ClaimPrice;
    Desc;
    GroupAVSounds;
    GroupID;
    GroupPrims;
    IsGroupOwned;
    LandingType;
    MaxPrims;
    MediaAutoScale;
    MediaID;
    MediaURL;
    MusicURL;
    Name;
    OtherCleanTime;
    OtherCount;
    OtherPrims;
    OwnerID;
    OwnerPrims;
    ParcelFlags;
    ParcelPrimBonus;
    PassHours;
    PassPrice;
    PublicCount;
    RegionDenyAnonymous;
    RegionDenyIdentified;
    RegionDenyTransacted;
    RegionPushOverride;
    RentPrice;
    RequestResult;
    SalePrice;
    SeeAvs;
    SelectedPrims;
    SelfCount;
    SequenceID;
    SimWideMaxPrims;
    SimWideTotalPrims;
    SnapSelection;
    SnapshotID;
    Status;
    TotalPrims;
    UserLocation;
    UserLookAt;
    RegionAllowAccessOverride;
}
exports.ParcelPropertiesEvent = ParcelPropertiesEvent;
//# sourceMappingURL=ParcelPropertiesEvent.js.map