"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimStatsEvent = void 0;
class SimStatsEvent {
    timeDilation;
    fps;
    physFPS;
    agentUPS;
    frameMS;
    netMS;
    simOtherMS;
    simPhysicsMS;
    agentMS;
    imagesMS;
    scriptMS;
    numTasks;
    numTasksActive;
    numAgentMain;
    numAgentChild;
    numScriptsActive;
    lslIPS;
    inPPS;
    outPPS;
    pendingDownloads;
    pendingUploads;
    virtualSizeKB;
    residentSizeKB;
    pendingLocalUploads;
    totalUnackedBytes;
    physicsPinnedTasks;
    physicsLODTasks;
    simPhysicsStepMS;
    simPhysicsShapeMS;
    simPhysicsOtherMS;
    simPhysicsMemory;
    scriptEPS;
    simSpareTime;
    simSleepTime;
    ioPumpTime;
    pctScriptsRun;
    regionIdle;
    regionIdlePossible;
    simAIStepTimeMS;
    skippedAISilStepsPS;
    pctSteppedCharacters;
}
exports.SimStatsEvent = SimStatsEvent;
//# sourceMappingURL=SimStatsEvent.js.map