extends RefCounted

## Parses avatar_skeleton.json and builds a shared Skeleton3D with all bones.
## SL coordinate conversion: (x,y,z) → Godot (x,z,-y).
## JSON generated by shared/convert-avatar-skeleton.js from avatar_skeleton.xml.

var _bones: Array = []  # [{name, parent, pos, rot, scale, cv}, ...] in parent-first order


func load_from_json(path: String) -> void:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		push_error("[SkeletonBuilder] Cannot open %s" % path)
		return
	var text: String = file.get_as_text()
	file.close()

	var parsed = JSON.parse_string(text)
	if parsed == null or not (parsed is Array):
		push_error("[SkeletonBuilder] Failed to parse JSON from %s" % path)
		return

	for entry: Dictionary in parsed:
		var pos_arr: Array = entry.get("pos", [0, 0, 0])
		var rot_arr: Array = entry.get("rot", [0, 0, 0])
		var scl_arr: Array = entry.get("scale", [1, 1, 1])
		_bones.append({
			"name": str(entry.get("name", "")),
			"parent_name": str(entry.get("parent", "")),
			"pos": Vector3(float(pos_arr[0]), float(pos_arr[1]), float(pos_arr[2])),
			"rot": Vector3(float(rot_arr[0]), float(rot_arr[1]), float(rot_arr[2])),
			"scale": Vector3(float(scl_arr[0]), float(scl_arr[1]), float(scl_arr[2])),
			"is_cv": bool(entry.get("cv", false)),
		})

	print("[SkeletonBuilder] Loaded %d bones from %s" % [_bones.size(), path])


## Create a new Skeleton3D with all bones from the parsed data.
func create_shared_skeleton() -> Skeleton3D:
	var skel := Skeleton3D.new()
	skel.name = "shared_skeleton"

	for bone_data: Dictionary in _bones:
		var idx := skel.add_bone(bone_data["name"])

		if not (bone_data["parent_name"] as String).is_empty():
			var parent_idx := skel.find_bone(bone_data["parent_name"])
			if parent_idx >= 0:
				skel.set_bone_parent(idx, parent_idx)

		var rest := Transform3D()
		# SL pos (x,y,z) → Godot (x,z,-y)
		# All bones use translation-only rests (Identity basis + position).
		# CV rotation/scale is baked into the GLB IBMs via Hippolyzer-style fixup.
		var sp: Vector3 = bone_data["pos"]
		rest.origin = Vector3(sp.x, sp.z, -sp.y)
		skel.set_bone_rest(idx, rest)

	return skel


## Returns {bone_name: Quaternion} of SL-space rest rotations for CV bones.
## Non-CV bones and CVs with zero rotation are omitted (implicitly Identity).
## Used by animation evaluation as the fallback rotation for unanimated CV bones,
## since their rest transforms are now translation-only (rotation baked into IBMs).
func get_sl_rest_rotations() -> Dictionary:
	var result := {}
	for bone_data: Dictionary in _bones:
		if not bone_data["is_cv"]:
			continue
		var rot_deg: Vector3 = bone_data["rot"]
		if rot_deg.is_zero_approx():
			continue
		# Build SL-space rotation from Euler angles (degrees XYZ order)
		var rx := deg_to_rad(rot_deg.x)
		var ry := deg_to_rad(rot_deg.y)
		var rz := deg_to_rad(rot_deg.z)
		var basis_sl := Basis.IDENTITY
		basis_sl = basis_sl.rotated(Vector3(1, 0, 0), rx)
		basis_sl = basis_sl.rotated(Vector3(0, 1, 0), ry)
		basis_sl = basis_sl.rotated(Vector3(0, 0, 1), rz)
		result[bone_data["name"]] = basis_sl.get_rotation_quaternion()
	return result


## Return the parsed bone data array for shape deformation baseline lookup.
func get_bone_data() -> Array:
	return _bones
