"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PCode = exports.BlendFunc = exports.SourcePattern = exports.TransferStatus = exports.FolderType = exports.AssetType = exports.InventoryType = exports.TextureAnimFlags = exports.SimAccessFlags = exports.ParcelFlags = exports.PrimFlags = exports.TextureFlags = exports.ParticleDataFlags = exports.RightsFlags = exports.RegionFlags = exports.TeleportFlags = exports.SoundFlags = exports.RegionProtocolFlags = exports.PacketFlags = exports.ParcelInfoFlags = exports.MessageFlags = exports.LoginFlags = exports.InventoryItemFlags = exports.InstantMessageEventFlags = exports.DecodeFlags = exports.ControlFlags = exports.CompressedFlags = exports.BotOptionFlags = exports.AgentFlags = exports.ExtraParams = exports.ParticleSystem = exports.LLSettings = exports.LLGestureWaitStep = exports.LLGestureChatStep = exports.LLGestureSoundStep = exports.LLGestureAnimationStep = exports.LLGesture = exports.LLGLTFMaterial = exports.LLLindenText = exports.LLWearable = exports.TextureEntry = exports.Utils = exports.Vector2 = exports.Vector3 = exports.UUID = exports.ChatSourceType = exports.BVH = exports.ClientEvents = exports.LoginParameters = exports.Bot = void 0;
exports.InventoryItem = exports.LLMesh = exports.MeshData = exports.SculptData = exports.Parcel = exports.Material = exports.GameObject = exports.LightImageData = exports.LightData = exports.FlexibleData = exports.Friend = exports.Avatar = exports.AvatarPropertiesReplyEvent = exports.GroupProfileReplyEvent = exports.ObjectUpdatedEvent = exports.ObjectKilledEvent = exports.NewObjectEvent = exports.ParcelPropertiesEvent = exports.ObjectPhysicsDataEvent = exports.FriendRemovedEvent = exports.FriendRightsEvent = exports.FriendOnlineEvent = exports.EventQueueStateChangeEvent = exports.ScriptDialogEvent = exports.TeleportEvent = exports.RegionInfoReplyEvent = exports.ParcelInfoReplyEvent = exports.MapInfoReplyEvent = exports.MapInfoRangeReplyEvent = exports.LureEvent = exports.InventoryOfferedEvent = exports.InstantMessageEvent = exports.GroupInviteEvent = exports.GroupNoticeEvent = exports.GroupChatSessionJoinEvent = exports.GroupChatSessionAgentListEvent = exports.GroupChatEvent = exports.FriendResponseEvent = exports.FriendRequestEvent = exports.DisconnectEvent = exports.ChatEvent = exports.LLGestureStepType = exports.Shininess = exports.SculptType = exports.ProfileShape = exports.PhysicsShapeType = exports.MappingType = exports.LayerType = exports.HoleType = exports.Bumpiness = void 0;
exports.RenderMaterialData = exports.ReflectionProbeData = exports.ExtendedMeshData = exports.TarWriter = exports.TarReader = void 0;
const Bot_1 = require("./Bot");
Object.defineProperty(exports, "Bot", { enumerable: true, get: function () { return Bot_1.Bot; } });
const LoginParameters_1 = require("./classes/LoginParameters");
Object.defineProperty(exports, "LoginParameters", { enumerable: true, get: function () { return LoginParameters_1.LoginParameters; } });
const ClientEvents_1 = require("./classes/ClientEvents");
Object.defineProperty(exports, "ClientEvents", { enumerable: true, get: function () { return ClientEvents_1.ClientEvents; } });
const BVH_1 = require("./classes/BVH");
Object.defineProperty(exports, "BVH", { enumerable: true, get: function () { return BVH_1.BVH; } });
const AssetType_1 = require("./enums/AssetType");
Object.defineProperty(exports, "AssetType", { enumerable: true, get: function () { return AssetType_1.AssetType; } });
;
const InstantMessageEventFlags_1 = require("./enums/InstantMessageEventFlags");
Object.defineProperty(exports, "InstantMessageEventFlags", { enumerable: true, get: function () { return InstantMessageEventFlags_1.InstantMessageEventFlags; } });
const InstantMessageEvent_1 = require("./events/InstantMessageEvent");
Object.defineProperty(exports, "InstantMessageEvent", { enumerable: true, get: function () { return InstantMessageEvent_1.InstantMessageEvent; } });
const ChatSourceType_1 = require("./enums/ChatSourceType");
Object.defineProperty(exports, "ChatSourceType", { enumerable: true, get: function () { return ChatSourceType_1.ChatSourceType; } });
const BotOptionFlags_1 = require("./enums/BotOptionFlags");
Object.defineProperty(exports, "BotOptionFlags", { enumerable: true, get: function () { return BotOptionFlags_1.BotOptionFlags; } });
const UUID_1 = require("./classes/UUID");
Object.defineProperty(exports, "UUID", { enumerable: true, get: function () { return UUID_1.UUID; } });
const Vector3_1 = require("./classes/Vector3");
Object.defineProperty(exports, "Vector3", { enumerable: true, get: function () { return Vector3_1.Vector3; } });
const ChatEvent_1 = require("./events/ChatEvent");
Object.defineProperty(exports, "ChatEvent", { enumerable: true, get: function () { return ChatEvent_1.ChatEvent; } });
const GroupInviteEvent_1 = require("./events/GroupInviteEvent");
Object.defineProperty(exports, "GroupInviteEvent", { enumerable: true, get: function () { return GroupInviteEvent_1.GroupInviteEvent; } });
const FriendRequestEvent_1 = require("./events/FriendRequestEvent");
Object.defineProperty(exports, "FriendRequestEvent", { enumerable: true, get: function () { return FriendRequestEvent_1.FriendRequestEvent; } });
const FriendResponseEvent_1 = require("./events/FriendResponseEvent");
Object.defineProperty(exports, "FriendResponseEvent", { enumerable: true, get: function () { return FriendResponseEvent_1.FriendResponseEvent; } });
const LureEvent_1 = require("./events/LureEvent");
Object.defineProperty(exports, "LureEvent", { enumerable: true, get: function () { return LureEvent_1.LureEvent; } });
const TeleportEvent_1 = require("./events/TeleportEvent");
Object.defineProperty(exports, "TeleportEvent", { enumerable: true, get: function () { return TeleportEvent_1.TeleportEvent; } });
const DisconnectEvent_1 = require("./events/DisconnectEvent");
Object.defineProperty(exports, "DisconnectEvent", { enumerable: true, get: function () { return DisconnectEvent_1.DisconnectEvent; } });
const GroupChatEvent_1 = require("./events/GroupChatEvent");
Object.defineProperty(exports, "GroupChatEvent", { enumerable: true, get: function () { return GroupChatEvent_1.GroupChatEvent; } });
const GroupChatSessionJoinEvent_1 = require("./events/GroupChatSessionJoinEvent");
Object.defineProperty(exports, "GroupChatSessionJoinEvent", { enumerable: true, get: function () { return GroupChatSessionJoinEvent_1.GroupChatSessionJoinEvent; } });
const GroupChatSessionAgentListEvent_1 = require("./events/GroupChatSessionAgentListEvent");
Object.defineProperty(exports, "GroupChatSessionAgentListEvent", { enumerable: true, get: function () { return GroupChatSessionAgentListEvent_1.GroupChatSessionAgentListEvent; } });
const GroupNoticeEvent_1 = require("./events/GroupNoticeEvent");
Object.defineProperty(exports, "GroupNoticeEvent", { enumerable: true, get: function () { return GroupNoticeEvent_1.GroupNoticeEvent; } });
const RegionInfoReplyEvent_1 = require("./events/RegionInfoReplyEvent");
Object.defineProperty(exports, "RegionInfoReplyEvent", { enumerable: true, get: function () { return RegionInfoReplyEvent_1.RegionInfoReplyEvent; } });
const MapInfoReplyEvent_1 = require("./events/MapInfoReplyEvent");
Object.defineProperty(exports, "MapInfoReplyEvent", { enumerable: true, get: function () { return MapInfoReplyEvent_1.MapInfoReplyEvent; } });
const MapInfoRangeReplyEvent_1 = require("./events/MapInfoRangeReplyEvent");
Object.defineProperty(exports, "MapInfoRangeReplyEvent", { enumerable: true, get: function () { return MapInfoRangeReplyEvent_1.MapInfoRangeReplyEvent; } });
const InventoryOfferedEvent_1 = require("./events/InventoryOfferedEvent");
Object.defineProperty(exports, "InventoryOfferedEvent", { enumerable: true, get: function () { return InventoryOfferedEvent_1.InventoryOfferedEvent; } });
const AgentFlags_1 = require("./enums/AgentFlags");
Object.defineProperty(exports, "AgentFlags", { enumerable: true, get: function () { return AgentFlags_1.AgentFlags; } });
const ControlFlags_1 = require("./enums/ControlFlags");
Object.defineProperty(exports, "ControlFlags", { enumerable: true, get: function () { return ControlFlags_1.ControlFlags; } });
const InventoryItemFlags_1 = require("./enums/InventoryItemFlags");
Object.defineProperty(exports, "InventoryItemFlags", { enumerable: true, get: function () { return InventoryItemFlags_1.InventoryItemFlags; } });
const LoginFlags_1 = require("./enums/LoginFlags");
Object.defineProperty(exports, "LoginFlags", { enumerable: true, get: function () { return LoginFlags_1.LoginFlags; } });
const MessageFlags_1 = require("./enums/MessageFlags");
Object.defineProperty(exports, "MessageFlags", { enumerable: true, get: function () { return MessageFlags_1.MessageFlags; } });
const PacketFlags_1 = require("./enums/PacketFlags");
Object.defineProperty(exports, "PacketFlags", { enumerable: true, get: function () { return PacketFlags_1.PacketFlags; } });
const RegionProtocolFlags_1 = require("./enums/RegionProtocolFlags");
Object.defineProperty(exports, "RegionProtocolFlags", { enumerable: true, get: function () { return RegionProtocolFlags_1.RegionProtocolFlags; } });
const SoundFlags_1 = require("./enums/SoundFlags");
Object.defineProperty(exports, "SoundFlags", { enumerable: true, get: function () { return SoundFlags_1.SoundFlags; } });
const TeleportFlags_1 = require("./enums/TeleportFlags");
Object.defineProperty(exports, "TeleportFlags", { enumerable: true, get: function () { return TeleportFlags_1.TeleportFlags; } });
const CompressedFlags_1 = require("./enums/CompressedFlags");
Object.defineProperty(exports, "CompressedFlags", { enumerable: true, get: function () { return CompressedFlags_1.CompressedFlags; } });
const DecodeFlags_1 = require("./enums/DecodeFlags");
Object.defineProperty(exports, "DecodeFlags", { enumerable: true, get: function () { return DecodeFlags_1.DecodeFlags; } });
const ParcelInfoFlags_1 = require("./enums/ParcelInfoFlags");
Object.defineProperty(exports, "ParcelInfoFlags", { enumerable: true, get: function () { return ParcelInfoFlags_1.ParcelInfoFlags; } });
const ParcelInfoReplyEvent_1 = require("./events/ParcelInfoReplyEvent");
Object.defineProperty(exports, "ParcelInfoReplyEvent", { enumerable: true, get: function () { return ParcelInfoReplyEvent_1.ParcelInfoReplyEvent; } });
const ScriptDialogEvent_1 = require("./events/ScriptDialogEvent");
Object.defineProperty(exports, "ScriptDialogEvent", { enumerable: true, get: function () { return ScriptDialogEvent_1.ScriptDialogEvent; } });
const EventQueueStateChangeEvent_1 = require("./events/EventQueueStateChangeEvent");
Object.defineProperty(exports, "EventQueueStateChangeEvent", { enumerable: true, get: function () { return EventQueueStateChangeEvent_1.EventQueueStateChangeEvent; } });
const RegionFlags_1 = require("./enums/RegionFlags");
Object.defineProperty(exports, "RegionFlags", { enumerable: true, get: function () { return RegionFlags_1.RegionFlags; } });
const Friend_1 = require("./classes/public/Friend");
Object.defineProperty(exports, "Friend", { enumerable: true, get: function () { return Friend_1.Friend; } });
const FriendOnlineEvent_1 = require("./events/FriendOnlineEvent");
Object.defineProperty(exports, "FriendOnlineEvent", { enumerable: true, get: function () { return FriendOnlineEvent_1.FriendOnlineEvent; } });
const Avatar_1 = require("./classes/public/Avatar");
Object.defineProperty(exports, "Avatar", { enumerable: true, get: function () { return Avatar_1.Avatar; } });
const RightsFlags_1 = require("./enums/RightsFlags");
Object.defineProperty(exports, "RightsFlags", { enumerable: true, get: function () { return RightsFlags_1.RightsFlags; } });
const FriendRightsEvent_1 = require("./events/FriendRightsEvent");
Object.defineProperty(exports, "FriendRightsEvent", { enumerable: true, get: function () { return FriendRightsEvent_1.FriendRightsEvent; } });
const FriendRemovedEvent_1 = require("./events/FriendRemovedEvent");
Object.defineProperty(exports, "FriendRemovedEvent", { enumerable: true, get: function () { return FriendRemovedEvent_1.FriendRemovedEvent; } });
const Vector2_1 = require("./classes/Vector2");
Object.defineProperty(exports, "Vector2", { enumerable: true, get: function () { return Vector2_1.Vector2; } });
const ParticleDataFlags_1 = require("./enums/ParticleDataFlags");
Object.defineProperty(exports, "ParticleDataFlags", { enumerable: true, get: function () { return ParticleDataFlags_1.ParticleDataFlags; } });
const TextureFlags_1 = require("./enums/TextureFlags");
Object.defineProperty(exports, "TextureFlags", { enumerable: true, get: function () { return TextureFlags_1.TextureFlags; } });
const SourcePattern_1 = require("./enums/SourcePattern");
Object.defineProperty(exports, "SourcePattern", { enumerable: true, get: function () { return SourcePattern_1.SourcePattern; } });
const BlendFunc_1 = require("./enums/BlendFunc");
Object.defineProperty(exports, "BlendFunc", { enumerable: true, get: function () { return BlendFunc_1.BlendFunc; } });
const PCode_1 = require("./enums/PCode");
Object.defineProperty(exports, "PCode", { enumerable: true, get: function () { return PCode_1.PCode; } });
const Utils_1 = require("./classes/Utils");
Object.defineProperty(exports, "Utils", { enumerable: true, get: function () { return Utils_1.Utils; } });
const ObjectPhysicsDataEvent_1 = require("./events/ObjectPhysicsDataEvent");
Object.defineProperty(exports, "ObjectPhysicsDataEvent", { enumerable: true, get: function () { return ObjectPhysicsDataEvent_1.ObjectPhysicsDataEvent; } });
const ParcelPropertiesEvent_1 = require("./events/ParcelPropertiesEvent");
Object.defineProperty(exports, "ParcelPropertiesEvent", { enumerable: true, get: function () { return ParcelPropertiesEvent_1.ParcelPropertiesEvent; } });
const PrimFlags_1 = require("./enums/PrimFlags");
Object.defineProperty(exports, "PrimFlags", { enumerable: true, get: function () { return PrimFlags_1.PrimFlags; } });
const TextureEntry_1 = require("./classes/TextureEntry");
Object.defineProperty(exports, "TextureEntry", { enumerable: true, get: function () { return TextureEntry_1.TextureEntry; } });
const Parcel_1 = require("./classes/public/Parcel");
Object.defineProperty(exports, "Parcel", { enumerable: true, get: function () { return Parcel_1.Parcel; } });
const Material_1 = require("./classes/public/Material");
Object.defineProperty(exports, "Material", { enumerable: true, get: function () { return Material_1.Material; } });
const GameObject_1 = require("./classes/public/GameObject");
Object.defineProperty(exports, "GameObject", { enumerable: true, get: function () { return GameObject_1.GameObject; } });
const LightImageData_1 = require("./classes/public/LightImageData");
Object.defineProperty(exports, "LightImageData", { enumerable: true, get: function () { return LightImageData_1.LightImageData; } });
const LightData_1 = require("./classes/public/LightData");
Object.defineProperty(exports, "LightData", { enumerable: true, get: function () { return LightData_1.LightData; } });
const FlexibleData_1 = require("./classes/public/FlexibleData");
Object.defineProperty(exports, "FlexibleData", { enumerable: true, get: function () { return FlexibleData_1.FlexibleData; } });
const MeshData_1 = require("./classes/public/MeshData");
Object.defineProperty(exports, "MeshData", { enumerable: true, get: function () { return MeshData_1.MeshData; } });
const SculptData_1 = require("./classes/public/SculptData");
Object.defineProperty(exports, "SculptData", { enumerable: true, get: function () { return SculptData_1.SculptData; } });
const NewObjectEvent_1 = require("./events/NewObjectEvent");
Object.defineProperty(exports, "NewObjectEvent", { enumerable: true, get: function () { return NewObjectEvent_1.NewObjectEvent; } });
const ObjectKilledEvent_1 = require("./events/ObjectKilledEvent");
Object.defineProperty(exports, "ObjectKilledEvent", { enumerable: true, get: function () { return ObjectKilledEvent_1.ObjectKilledEvent; } });
const ObjectUpdatedEvent_1 = require("./events/ObjectUpdatedEvent");
Object.defineProperty(exports, "ObjectUpdatedEvent", { enumerable: true, get: function () { return ObjectUpdatedEvent_1.ObjectUpdatedEvent; } });
const GroupProfileReplyEvent_1 = require("./events/GroupProfileReplyEvent");
Object.defineProperty(exports, "GroupProfileReplyEvent", { enumerable: true, get: function () { return GroupProfileReplyEvent_1.GroupProfileReplyEvent; } });
const AvatarPropertiesReplyEvent_1 = require("./events/AvatarPropertiesReplyEvent");
Object.defineProperty(exports, "AvatarPropertiesReplyEvent", { enumerable: true, get: function () { return AvatarPropertiesReplyEvent_1.AvatarPropertiesReplyEvent; } });
const Bumpiness_1 = require("./enums/Bumpiness");
Object.defineProperty(exports, "Bumpiness", { enumerable: true, get: function () { return Bumpiness_1.Bumpiness; } });
const HoleType_1 = require("./enums/HoleType");
Object.defineProperty(exports, "HoleType", { enumerable: true, get: function () { return HoleType_1.HoleType; } });
const LayerType_1 = require("./enums/LayerType");
Object.defineProperty(exports, "LayerType", { enumerable: true, get: function () { return LayerType_1.LayerType; } });
const MappingType_1 = require("./enums/MappingType");
Object.defineProperty(exports, "MappingType", { enumerable: true, get: function () { return MappingType_1.MappingType; } });
const PhysicsShapeType_1 = require("./enums/PhysicsShapeType");
Object.defineProperty(exports, "PhysicsShapeType", { enumerable: true, get: function () { return PhysicsShapeType_1.PhysicsShapeType; } });
const ParcelFlags_1 = require("./enums/ParcelFlags");
Object.defineProperty(exports, "ParcelFlags", { enumerable: true, get: function () { return ParcelFlags_1.ParcelFlags; } });
const ProfileShape_1 = require("./enums/ProfileShape");
Object.defineProperty(exports, "ProfileShape", { enumerable: true, get: function () { return ProfileShape_1.ProfileShape; } });
const SculptType_1 = require("./enums/SculptType");
Object.defineProperty(exports, "SculptType", { enumerable: true, get: function () { return SculptType_1.SculptType; } });
const Shininess_1 = require("./enums/Shininess");
Object.defineProperty(exports, "Shininess", { enumerable: true, get: function () { return Shininess_1.Shininess; } });
const SimAccessFlags_1 = require("./enums/SimAccessFlags");
Object.defineProperty(exports, "SimAccessFlags", { enumerable: true, get: function () { return SimAccessFlags_1.SimAccessFlags; } });
const TextureAnimFlags_1 = require("./enums/TextureAnimFlags");
Object.defineProperty(exports, "TextureAnimFlags", { enumerable: true, get: function () { return TextureAnimFlags_1.TextureAnimFlags; } });
const TransferStatus_1 = require("./enums/TransferStatus");
Object.defineProperty(exports, "TransferStatus", { enumerable: true, get: function () { return TransferStatus_1.TransferStatus; } });
const LLWearable_1 = require("./classes/LLWearable");
Object.defineProperty(exports, "LLWearable", { enumerable: true, get: function () { return LLWearable_1.LLWearable; } });
const ParticleSystem_1 = require("./classes/ParticleSystem");
Object.defineProperty(exports, "ParticleSystem", { enumerable: true, get: function () { return ParticleSystem_1.ParticleSystem; } });
const ExtraParams_1 = require("./classes/public/ExtraParams");
Object.defineProperty(exports, "ExtraParams", { enumerable: true, get: function () { return ExtraParams_1.ExtraParams; } });
const LLMesh_1 = require("./classes/public/LLMesh");
Object.defineProperty(exports, "LLMesh", { enumerable: true, get: function () { return LLMesh_1.LLMesh; } });
const FolderType_1 = require("./enums/FolderType");
Object.defineProperty(exports, "FolderType", { enumerable: true, get: function () { return FolderType_1.FolderType; } });
const InventoryItem_1 = require("./classes/InventoryItem");
Object.defineProperty(exports, "InventoryItem", { enumerable: true, get: function () { return InventoryItem_1.InventoryItem; } });
const InventoryType_1 = require("./enums/InventoryType");
Object.defineProperty(exports, "InventoryType", { enumerable: true, get: function () { return InventoryType_1.InventoryType; } });
const TarWriter_1 = require("./classes/TarWriter");
Object.defineProperty(exports, "TarWriter", { enumerable: true, get: function () { return TarWriter_1.TarWriter; } });
const TarReader_1 = require("./classes/TarReader");
Object.defineProperty(exports, "TarReader", { enumerable: true, get: function () { return TarReader_1.TarReader; } });
const LLGesture_1 = require("./classes/LLGesture");
Object.defineProperty(exports, "LLGesture", { enumerable: true, get: function () { return LLGesture_1.LLGesture; } });
const LLGestureAnimationStep_1 = require("./classes/LLGestureAnimationStep");
Object.defineProperty(exports, "LLGestureAnimationStep", { enumerable: true, get: function () { return LLGestureAnimationStep_1.LLGestureAnimationStep; } });
const LLGestureSoundStep_1 = require("./classes/LLGestureSoundStep");
Object.defineProperty(exports, "LLGestureSoundStep", { enumerable: true, get: function () { return LLGestureSoundStep_1.LLGestureSoundStep; } });
const LLGestureWaitStep_1 = require("./classes/LLGestureWaitStep");
Object.defineProperty(exports, "LLGestureWaitStep", { enumerable: true, get: function () { return LLGestureWaitStep_1.LLGestureWaitStep; } });
const LLGestureChatStep_1 = require("./classes/LLGestureChatStep");
Object.defineProperty(exports, "LLGestureChatStep", { enumerable: true, get: function () { return LLGestureChatStep_1.LLGestureChatStep; } });
const LLGestureStepType_1 = require("./enums/LLGestureStepType");
Object.defineProperty(exports, "LLGestureStepType", { enumerable: true, get: function () { return LLGestureStepType_1.LLGestureStepType; } });
const LLLindenText_1 = require("./classes/LLLindenText");
Object.defineProperty(exports, "LLLindenText", { enumerable: true, get: function () { return LLLindenText_1.LLLindenText; } });
const LLGLTFMaterial_1 = require("./classes/LLGLTFMaterial");
Object.defineProperty(exports, "LLGLTFMaterial", { enumerable: true, get: function () { return LLGLTFMaterial_1.LLGLTFMaterial; } });
const ExtendedMeshData_1 = require("./classes/public/ExtendedMeshData");
Object.defineProperty(exports, "ExtendedMeshData", { enumerable: true, get: function () { return ExtendedMeshData_1.ExtendedMeshData; } });
const ReflectionProbeData_1 = require("./classes/public/ReflectionProbeData");
Object.defineProperty(exports, "ReflectionProbeData", { enumerable: true, get: function () { return ReflectionProbeData_1.ReflectionProbeData; } });
const RenderMaterialData_1 = require("./classes/public/RenderMaterialData");
Object.defineProperty(exports, "RenderMaterialData", { enumerable: true, get: function () { return RenderMaterialData_1.RenderMaterialData; } });
const LLSettings_1 = require("./classes/LLSettings");
Object.defineProperty(exports, "LLSettings", { enumerable: true, get: function () { return LLSettings_1.LLSettings; } });
//# sourceMappingURL=index.js.map