"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentFOVMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class AgentFOVMessage {
    name = 'AgentFOV';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.AgentFOV;
    AgentData;
    FOVBlock;
    getSize() {
        return 44;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentData['SessionID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt32LE(this.AgentData['CircuitCode'], pos);
        pos += 4;
        buf.writeUInt32LE(this.FOVBlock['GenCounter'], pos);
        pos += 4;
        buf.writeFloatLE(this.FOVBlock['VerticalAngle'], pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjAgentData = {
            AgentID: UUID_1.UUID.zero(),
            SessionID: UUID_1.UUID.zero(),
            CircuitCode: 0
        };
        newObjAgentData['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAgentData['SessionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAgentData['CircuitCode'] = buf.readUInt32LE(pos);
        pos += 4;
        this.AgentData = newObjAgentData;
        const newObjFOVBlock = {
            GenCounter: 0,
            VerticalAngle: 0
        };
        newObjFOVBlock['GenCounter'] = buf.readUInt32LE(pos);
        pos += 4;
        newObjFOVBlock['VerticalAngle'] = buf.readFloatLE(pos);
        pos += 4;
        this.FOVBlock = newObjFOVBlock;
        return pos - startPos;
    }
}
exports.AgentFOVMessage = AgentFOVMessage;
//# sourceMappingURL=AgentFOV.js.map