"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertMessageMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class AlertMessageMessage {
    name = 'AlertMessage';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.AlertMessage;
    AlertData;
    AlertInfo;
    getSize() {
        return (this.AlertData['Message'].length + 1) + this.calculateVarVarSize(this.AlertInfo, 'Message', 1) + this.calculateVarVarSize(this.AlertInfo, 'ExtraParams', 1) + 1;
    }
    calculateVarVarSize(block, paramName, extraPerVar) {
        let size = 0;
        for (const bl of block) {
            size += bl[paramName].length + extraPerVar;
        }
        return size;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeUInt8(this.AlertData['Message'].length, pos++);
        this.AlertData['Message'].copy(buf, pos);
        pos += this.AlertData['Message'].length;
        const count = this.AlertInfo.length;
        buf.writeUInt8(this.AlertInfo.length, pos++);
        for (let i = 0; i < count; i++) {
            buf.writeUInt8(this.AlertInfo[i]['Message'].length, pos++);
            this.AlertInfo[i]['Message'].copy(buf, pos);
            pos += this.AlertInfo[i]['Message'].length;
            buf.writeUInt8(this.AlertInfo[i]['ExtraParams'].length, pos++);
            this.AlertInfo[i]['ExtraParams'].copy(buf, pos);
            pos += this.AlertInfo[i]['ExtraParams'].length;
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        const newObjAlertData = {
            Message: Buffer.allocUnsafe(0)
        };
        varLength = buf.readUInt8(pos++);
        newObjAlertData['Message'] = buf.slice(pos, pos + varLength);
        pos += varLength;
        this.AlertData = newObjAlertData;
        if (pos >= buf.length) {
            return pos - startPos;
        }
        const count = buf.readUInt8(pos++);
        this.AlertInfo = [];
        for (let i = 0; i < count; i++) {
            const newObjAlertInfo = {
                Message: Buffer.allocUnsafe(0),
                ExtraParams: Buffer.allocUnsafe(0)
            };
            varLength = buf.readUInt8(pos++);
            newObjAlertInfo['Message'] = buf.slice(pos, pos + varLength);
            pos += varLength;
            varLength = buf.readUInt8(pos++);
            newObjAlertInfo['ExtraParams'] = buf.slice(pos, pos + varLength);
            pos += varLength;
            this.AlertInfo.push(newObjAlertInfo);
        }
        return pos - startPos;
    }
}
exports.AlertMessageMessage = AlertMessageMessage;
//# sourceMappingURL=AlertMessage.js.map