"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloseCircuitMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class CloseCircuitMessage {
    name = 'CloseCircuit';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyFixed;
    id = Message_1.Message.CloseCircuit;
    getSize() {
        return 0;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        return 0;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        return 0;
    }
}
exports.CloseCircuitMessage = CloseCircuitMessage;
//# sourceMappingURL=CloseCircuit.js.map