"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfirmAuctionStartMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class ConfirmAuctionStartMessage {
    name = 'ConfirmAuctionStart';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.ConfirmAuctionStart;
    AuctionData;
    getSize() {
        return 20;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.AuctionData['ParcelID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt32LE(this.AuctionData['AuctionID'], pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjAuctionData = {
            ParcelID: UUID_1.UUID.zero(),
            AuctionID: 0
        };
        newObjAuctionData['ParcelID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAuctionData['AuctionID'] = buf.readUInt32LE(pos);
        pos += 4;
        this.AuctionData = newObjAuctionData;
        return pos - startPos;
    }
}
exports.ConfirmAuctionStartMessage = ConfirmAuctionStartMessage;
//# sourceMappingURL=ConfirmAuctionStart.js.map