"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CrossedRegionMessage = void 0;
const UUID_1 = require("../UUID");
const IPAddress_1 = require("../IPAddress");
const Vector3_1 = require("../Vector3");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class CrossedRegionMessage {
    name = 'CrossedRegion';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.Blacklisted | MessageFlags_1.MessageFlags.FrequencyMedium;
    id = Message_1.Message.CrossedRegion;
    AgentData;
    RegionData;
    Info;
    getSize() {
        return (this.RegionData['SeedCapability'].length + 2) + 70;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentData['SessionID'].writeToBuffer(buf, pos);
        pos += 16;
        this.RegionData['SimIP'].writeToBuffer(buf, pos);
        pos += 4;
        buf.writeUInt16LE(this.RegionData['SimPort'], pos);
        pos += 2;
        buf.writeInt32LE(this.RegionData['RegionHandle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.RegionData['RegionHandle'].high, pos);
        pos += 4;
        buf.writeUInt16LE(this.RegionData['SeedCapability'].length, pos);
        pos += 2;
        this.RegionData['SeedCapability'].copy(buf, pos);
        pos += this.RegionData['SeedCapability'].length;
        this.Info['Position'].writeToBuffer(buf, pos, false);
        pos += 12;
        this.Info['LookAt'].writeToBuffer(buf, pos, false);
        pos += 12;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        const newObjAgentData = {
            AgentID: UUID_1.UUID.zero(),
            SessionID: UUID_1.UUID.zero()
        };
        newObjAgentData['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAgentData['SessionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.AgentData = newObjAgentData;
        const newObjRegionData = {
            SimIP: IPAddress_1.IPAddress.zero(),
            SimPort: 0,
            RegionHandle: long_1.default.ZERO,
            SeedCapability: Buffer.allocUnsafe(0)
        };
        newObjRegionData['SimIP'] = new IPAddress_1.IPAddress(buf, pos);
        pos += 4;
        newObjRegionData['SimPort'] = buf.readUInt16LE(pos);
        pos += 2;
        newObjRegionData['RegionHandle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        varLength = buf.readUInt16LE(pos);
        pos += 2;
        newObjRegionData['SeedCapability'] = buf.slice(pos, pos + varLength);
        pos += varLength;
        this.RegionData = newObjRegionData;
        const newObjInfo = {
            Position: Vector3_1.Vector3.getZero(),
            LookAt: Vector3_1.Vector3.getZero()
        };
        newObjInfo['Position'] = new Vector3_1.Vector3(buf, pos, false);
        pos += 12;
        newObjInfo['LookAt'] = new Vector3_1.Vector3(buf, pos, false);
        pos += 12;
        this.Info = newObjInfo;
        return pos - startPos;
    }
}
exports.CrossedRegionMessage = CrossedRegionMessage;
//# sourceMappingURL=CrossedRegion.js.map