"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.DisableSimulatorMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class DisableSimulatorMessage {
    name = 'DisableSimulator';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.DisableSimulator;
    getSize() {
        return 0;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        return 0;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        return 0;
    }
}
exports.DisableSimulatorMessage = DisableSimulatorMessage;
//# sourceMappingURL=DisableSimulator.js.map