"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnableSimulatorMessage = void 0;
const IPAddress_1 = require("../IPAddress");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class EnableSimulatorMessage {
    name = 'EnableSimulator';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.Blacklisted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.EnableSimulator;
    SimulatorInfo;
    getSize() {
        return 14;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeInt32LE(this.SimulatorInfo['Handle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.SimulatorInfo['Handle'].high, pos);
        pos += 4;
        this.SimulatorInfo['IP'].writeToBuffer(buf, pos);
        pos += 4;
        buf.writeUInt16LE(this.SimulatorInfo['Port'], pos);
        pos += 2;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjSimulatorInfo = {
            Handle: long_1.default.ZERO,
            IP: IPAddress_1.IPAddress.zero(),
            Port: 0
        };
        newObjSimulatorInfo['Handle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        newObjSimulatorInfo['IP'] = new IPAddress_1.IPAddress(buf, pos);
        pos += 4;
        newObjSimulatorInfo['Port'] = buf.readUInt16LE(pos);
        pos += 2;
        this.SimulatorInfo = newObjSimulatorInfo;
        return pos - startPos;
    }
}
exports.EnableSimulatorMessage = EnableSimulatorMessage;
//# sourceMappingURL=EnableSimulator.js.map