"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.FormFriendshipMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class FormFriendshipMessage {
    name = 'FormFriendship';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.FormFriendship;
    AgentBlock;
    getSize() {
        return 32;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.AgentBlock['SourceID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentBlock['DestID'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjAgentBlock = {
            SourceID: UUID_1.UUID.zero(),
            DestID: UUID_1.UUID.zero()
        };
        newObjAgentBlock['SourceID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAgentBlock['DestID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.AgentBlock = newObjAgentBlock;
        return pos - startPos;
    }
}
exports.FormFriendshipMessage = FormFriendshipMessage;
//# sourceMappingURL=FormFriendship.js.map