"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.GenericStreamingMessageMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class GenericStreamingMessageMessage {
    name = 'GenericStreamingMessage';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyHigh;
    id = Message_1.Message.GenericStreamingMessage;
    MethodData;
    DataBlock;
    getSize() {
        return (this.DataBlock['Data'].length + 2) + 2;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeUInt16LE(this.MethodData['Method'], pos);
        pos += 2;
        buf.writeUInt16LE(this.DataBlock['Data'].length, pos);
        pos += 2;
        this.DataBlock['Data'].copy(buf, pos);
        pos += this.DataBlock['Data'].length;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        const newObjMethodData = {
            Method: 0
        };
        newObjMethodData['Method'] = buf.readUInt16LE(pos);
        pos += 2;
        this.MethodData = newObjMethodData;
        const newObjDataBlock = {
            Data: Buffer.allocUnsafe(0)
        };
        varLength = buf.readUInt16LE(pos);
        pos += 2;
        newObjDataBlock['Data'] = buf.slice(pos, pos + varLength);
        pos += varLength;
        this.DataBlock = newObjDataBlock;
        return pos - startPos;
    }
}
exports.GenericStreamingMessageMessage = GenericStreamingMessageMessage;
//# sourceMappingURL=GenericStreamingMessage.js.map