"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.GrantUserRightsMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class GrantUserRightsMessage {
    name = 'GrantUserRights';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.GrantUserRights;
    AgentData;
    Rights;
    getSize() {
        return ((20) * this.Rights.length) + 33;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentData['SessionID'].writeToBuffer(buf, pos);
        pos += 16;
        const count = this.Rights.length;
        buf.writeUInt8(this.Rights.length, pos++);
        for (let i = 0; i < count; i++) {
            this.Rights[i]['AgentRelated'].writeToBuffer(buf, pos);
            pos += 16;
            buf.writeInt32LE(this.Rights[i]['RelatedRights'], pos);
            pos += 4;
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjAgentData = {
            AgentID: UUID_1.UUID.zero(),
            SessionID: UUID_1.UUID.zero()
        };
        newObjAgentData['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAgentData['SessionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.AgentData = newObjAgentData;
        if (pos >= buf.length) {
            return pos - startPos;
        }
        const count = buf.readUInt8(pos++);
        this.Rights = [];
        for (let i = 0; i < count; i++) {
            const newObjRights = {
                AgentRelated: UUID_1.UUID.zero(),
                RelatedRights: 0
            };
            newObjRights['AgentRelated'] = new UUID_1.UUID(buf, pos);
            pos += 16;
            newObjRights['RelatedRights'] = buf.readInt32LE(pos);
            pos += 4;
            this.Rights.push(newObjRights);
        }
        return pos - startPos;
    }
}
exports.GrantUserRightsMessage = GrantUserRightsMessage;
//# sourceMappingURL=GrantUserRights.js.map