"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.HealthMessageMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class HealthMessageMessage {
    name = 'HealthMessage';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.Zerocoded | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.HealthMessage;
    HealthData;
    getSize() {
        return 4;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeFloatLE(this.HealthData['Health'], pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjHealthData = {
            Health: 0
        };
        newObjHealthData['Health'] = buf.readFloatLE(pos);
        pos += 4;
        this.HealthData = newObjHealthData;
        return pos - startPos;
    }
}
exports.HealthMessageMessage = HealthMessageMessage;
//# sourceMappingURL=HealthMessage.js.map