"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImageNotInDatabaseMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class ImageNotInDatabaseMessage {
    name = 'ImageNotInDatabase';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.ImageNotInDatabase;
    ImageID;
    getSize() {
        return 16;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.ImageID['ID'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjImageID = {
            ID: UUID_1.UUID.zero()
        };
        newObjImageID['ID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.ImageID = newObjImageID;
        return pos - startPos;
    }
}
exports.ImageNotInDatabaseMessage = ImageNotInDatabaseMessage;
//# sourceMappingURL=ImageNotInDatabase.js.map