"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.InviteGroupResponseMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class InviteGroupResponseMessage {
    name = 'InviteGroupResponse';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.InviteGroupResponse;
    InviteData;
    getSize() {
        return 68;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.InviteData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.InviteData['InviteeID'].writeToBuffer(buf, pos);
        pos += 16;
        this.InviteData['GroupID'].writeToBuffer(buf, pos);
        pos += 16;
        this.InviteData['RoleID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeInt32LE(this.InviteData['MembershipFee'], pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjInviteData = {
            AgentID: UUID_1.UUID.zero(),
            InviteeID: UUID_1.UUID.zero(),
            GroupID: UUID_1.UUID.zero(),
            RoleID: UUID_1.UUID.zero(),
            MembershipFee: 0
        };
        newObjInviteData['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjInviteData['InviteeID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjInviteData['GroupID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjInviteData['RoleID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjInviteData['MembershipFee'] = buf.readInt32LE(pos);
        pos += 4;
        this.InviteData = newObjInviteData;
        return pos - startPos;
    }
}
exports.InviteGroupResponseMessage = InviteGroupResponseMessage;
//# sourceMappingURL=InviteGroupResponse.js.map