"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.KillChildAgentsMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class KillChildAgentsMessage {
    name = 'KillChildAgents';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.KillChildAgents;
    IDBlock;
    getSize() {
        return 16;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.IDBlock['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjIDBlock = {
            AgentID: UUID_1.UUID.zero()
        };
        newObjIDBlock['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.IDBlock = newObjIDBlock;
        return pos - startPos;
    }
}
exports.KillChildAgentsMessage = KillChildAgentsMessage;
//# sourceMappingURL=KillChildAgents.js.map