"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.LayerDataMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class LayerDataMessage {
    name = 'LayerData';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyHigh;
    id = Message_1.Message.LayerData;
    LayerID;
    LayerData;
    getSize() {
        return (this.LayerData['Data'].length + 2) + 1;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeUInt8(this.LayerID['Type'], pos++);
        buf.writeUInt16LE(this.LayerData['Data'].length, pos);
        pos += 2;
        this.LayerData['Data'].copy(buf, pos);
        pos += this.LayerData['Data'].length;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        const newObjLayerID = {
            Type: 0
        };
        newObjLayerID['Type'] = buf.readUInt8(pos++);
        this.LayerID = newObjLayerID;
        const newObjLayerData = {
            Data: Buffer.allocUnsafe(0)
        };
        varLength = buf.readUInt16LE(pos);
        pos += 2;
        newObjLayerData['Data'] = buf.slice(pos, pos + varLength);
        pos += varLength;
        this.LayerData = newObjLayerData;
        return pos - startPos;
    }
}
exports.LayerDataMessage = LayerDataMessage;
//# sourceMappingURL=LayerData.js.map