"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.NearestLandingRegionReplyMessage = void 0;
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class NearestLandingRegionReplyMessage {
    name = 'NearestLandingRegionReply';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.NearestLandingRegionReply;
    LandingRegionData;
    getSize() {
        return 8;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeInt32LE(this.LandingRegionData['RegionHandle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.LandingRegionData['RegionHandle'].high, pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjLandingRegionData = {
            RegionHandle: long_1.default.ZERO
        };
        newObjLandingRegionData['RegionHandle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        this.LandingRegionData = newObjLandingRegionData;
        return pos - startPos;
    }
}
exports.NearestLandingRegionReplyMessage = NearestLandingRegionReplyMessage;
//# sourceMappingURL=NearestLandingRegionReply.js.map