"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.NearestLandingRegionRequestMessage = void 0;
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class NearestLandingRegionRequestMessage {
    name = 'NearestLandingRegionRequest';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.NearestLandingRegionRequest;
    RequestingRegionData;
    getSize() {
        return 8;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeInt32LE(this.RequestingRegionData['RegionHandle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.RequestingRegionData['RegionHandle'].high, pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjRequestingRegionData = {
            RegionHandle: long_1.default.ZERO
        };
        newObjRequestingRegionData['RegionHandle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        this.RequestingRegionData = newObjRequestingRegionData;
        return pos - startPos;
    }
}
exports.NearestLandingRegionRequestMessage = NearestLandingRegionRequestMessage;
//# sourceMappingURL=NearestLandingRegionRequest.js.map