"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.NeighborListMessage = void 0;
const UUID_1 = require("../UUID");
const IPAddress_1 = require("../IPAddress");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class NeighborListMessage {
    name = 'NeighborList';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyHigh;
    id = Message_1.Message.NeighborList;
    NeighborBlock;
    getSize() {
        return this.calculateVarVarSize(this.NeighborBlock, 'Name', 1) + 116;
    }
    calculateVarVarSize(block, paramName, extraPerVar) {
        let size = 0;
        for (const bl of block) {
            size += bl[paramName].length + extraPerVar;
        }
        return size;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        const count = 4;
        for (let i = 0; i < count; i++) {
            this.NeighborBlock[i]['IP'].writeToBuffer(buf, pos);
            pos += 4;
            buf.writeUInt16LE(this.NeighborBlock[i]['Port'], pos);
            pos += 2;
            this.NeighborBlock[i]['PublicIP'].writeToBuffer(buf, pos);
            pos += 4;
            buf.writeUInt16LE(this.NeighborBlock[i]['PublicPort'], pos);
            pos += 2;
            this.NeighborBlock[i]['RegionID'].writeToBuffer(buf, pos);
            pos += 16;
            buf.writeUInt8(this.NeighborBlock[i]['Name'].length, pos++);
            this.NeighborBlock[i]['Name'].copy(buf, pos);
            pos += this.NeighborBlock[i]['Name'].length;
            buf.writeUInt8(this.NeighborBlock[i]['SimAccess'], pos++);
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        const count = 4;
        this.NeighborBlock = [];
        for (let i = 0; i < count; i++) {
            const newObjNeighborBlock = {
                IP: IPAddress_1.IPAddress.zero(),
                Port: 0,
                PublicIP: IPAddress_1.IPAddress.zero(),
                PublicPort: 0,
                RegionID: UUID_1.UUID.zero(),
                Name: Buffer.allocUnsafe(0),
                SimAccess: 0
            };
            newObjNeighborBlock['IP'] = new IPAddress_1.IPAddress(buf, pos);
            pos += 4;
            newObjNeighborBlock['Port'] = buf.readUInt16LE(pos);
            pos += 2;
            newObjNeighborBlock['PublicIP'] = new IPAddress_1.IPAddress(buf, pos);
            pos += 4;
            newObjNeighborBlock['PublicPort'] = buf.readUInt16LE(pos);
            pos += 2;
            newObjNeighborBlock['RegionID'] = new UUID_1.UUID(buf, pos);
            pos += 16;
            varLength = buf.readUInt8(pos++);
            newObjNeighborBlock['Name'] = buf.slice(pos, pos + varLength);
            pos += varLength;
            newObjNeighborBlock['SimAccess'] = buf.readUInt8(pos++);
            this.NeighborBlock.push(newObjNeighborBlock);
        }
        return pos - startPos;
    }
}
exports.NeighborListMessage = NeighborListMessage;
//# sourceMappingURL=NeighborList.js.map