"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.NetTestMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class NetTestMessage {
    name = 'NetTest';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.NetTest;
    NetBlock;
    getSize() {
        return 2;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeUInt16LE(this.NetBlock['Port'], pos);
        pos += 2;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjNetBlock = {
            Port: 0
        };
        newObjNetBlock['Port'] = buf.readUInt16LE(pos);
        pos += 2;
        this.NetBlock = newObjNetBlock;
        return pos - startPos;
    }
}
exports.NetTestMessage = NetTestMessage;
//# sourceMappingURL=NetTest.js.map