"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpenCircuitMessage = void 0;
const IPAddress_1 = require("../IPAddress");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class OpenCircuitMessage {
    name = 'OpenCircuit';
    messageFlags = MessageFlags_1.MessageFlags.Blacklisted | MessageFlags_1.MessageFlags.FrequencyFixed;
    id = Message_1.Message.OpenCircuit;
    CircuitInfo;
    getSize() {
        return 6;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.CircuitInfo['IP'].writeToBuffer(buf, pos);
        pos += 4;
        buf.writeUInt16LE(this.CircuitInfo['Port'], pos);
        pos += 2;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjCircuitInfo = {
            IP: IPAddress_1.IPAddress.zero(),
            Port: 0
        };
        newObjCircuitInfo['IP'] = new IPAddress_1.IPAddress(buf, pos);
        pos += 4;
        newObjCircuitInfo['Port'] = buf.readUInt16LE(pos);
        pos += 2;
        this.CircuitInfo = newObjCircuitInfo;
        return pos - startPos;
    }
}
exports.OpenCircuitMessage = OpenCircuitMessage;
//# sourceMappingURL=OpenCircuit.js.map