"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.PacketAckMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class PacketAckMessage {
    name = 'PacketAck';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyFixed;
    id = Message_1.Message.PacketAck;
    Packets;
    getSize() {
        return ((4) * this.Packets.length) + 1;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        const count = this.Packets.length;
        buf.writeUInt8(this.Packets.length, pos++);
        for (let i = 0; i < count; i++) {
            buf.writeUInt32LE(this.Packets[i]['ID'], pos);
            pos += 4;
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        if (pos >= buf.length) {
            return pos - startPos;
        }
        const count = buf.readUInt8(pos++);
        this.Packets = [];
        for (let i = 0; i < count; i++) {
            const newObjPackets = {
                ID: 0
            };
            newObjPackets['ID'] = buf.readUInt32LE(pos);
            pos += 4;
            this.Packets.push(newObjPackets);
        }
        return pos - startPos;
    }
}
exports.PacketAckMessage = PacketAckMessage;
//# sourceMappingURL=PacketAck.js.map