"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.ParcelObjectOwnersReplyMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class ParcelObjectOwnersReplyMessage {
    name = 'ParcelObjectOwnersReply';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.Zerocoded | MessageFlags_1.MessageFlags.Deprecated | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.ParcelObjectOwnersReply;
    Data;
    getSize() {
        return ((22) * this.Data.length) + 1;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        const count = this.Data.length;
        buf.writeUInt8(this.Data.length, pos++);
        for (let i = 0; i < count; i++) {
            this.Data[i]['OwnerID'].writeToBuffer(buf, pos);
            pos += 16;
            buf.writeUInt8((this.Data[i]['IsGroupOwned']) ? 1 : 0, pos++);
            buf.writeInt32LE(this.Data[i]['Count'], pos);
            pos += 4;
            buf.writeUInt8((this.Data[i]['OnlineStatus']) ? 1 : 0, pos++);
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        if (pos >= buf.length) {
            return pos - startPos;
        }
        const count = buf.readUInt8(pos++);
        this.Data = [];
        for (let i = 0; i < count; i++) {
            const newObjData = {
                OwnerID: UUID_1.UUID.zero(),
                IsGroupOwned: false,
                Count: 0,
                OnlineStatus: false
            };
            newObjData['OwnerID'] = new UUID_1.UUID(buf, pos);
            pos += 16;
            newObjData['IsGroupOwned'] = (buf.readUInt8(pos++) === 1);
            newObjData['Count'] = buf.readInt32LE(pos);
            pos += 4;
            newObjData['OnlineStatus'] = (buf.readUInt8(pos++) === 1);
            this.Data.push(newObjData);
        }
        return pos - startPos;
    }
}
exports.ParcelObjectOwnersReplyMessage = ParcelObjectOwnersReplyMessage;
//# sourceMappingURL=ParcelObjectOwnersReply.js.map