"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.ParcelMediaCommandMessageMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class ParcelMediaCommandMessageMessage {
    name = 'ParcelMediaCommandMessage';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.ParcelMediaCommandMessage;
    CommandBlock;
    getSize() {
        return 12;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeUInt32LE(this.CommandBlock['Flags'], pos);
        pos += 4;
        buf.writeUInt32LE(this.CommandBlock['Command'], pos);
        pos += 4;
        buf.writeFloatLE(this.CommandBlock['Time'], pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjCommandBlock = {
            Flags: 0,
            Command: 0,
            Time: 0
        };
        newObjCommandBlock['Flags'] = buf.readUInt32LE(pos);
        pos += 4;
        newObjCommandBlock['Command'] = buf.readUInt32LE(pos);
        pos += 4;
        newObjCommandBlock['Time'] = buf.readFloatLE(pos);
        pos += 4;
        this.CommandBlock = newObjCommandBlock;
        return pos - startPos;
    }
}
exports.ParcelMediaCommandMessageMessage = ParcelMediaCommandMessageMessage;
//# sourceMappingURL=ParcelMediaCommandMessage.js.map