"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegionPresenceRequestByRegionIDMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class RegionPresenceRequestByRegionIDMessage {
    name = 'RegionPresenceRequestByRegionID';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.RegionPresenceRequestByRegionID;
    RegionData;
    getSize() {
        return ((16) * this.RegionData.length) + 1;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        const count = this.RegionData.length;
        buf.writeUInt8(this.RegionData.length, pos++);
        for (let i = 0; i < count; i++) {
            this.RegionData[i]['RegionID'].writeToBuffer(buf, pos);
            pos += 16;
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        if (pos >= buf.length) {
            return pos - startPos;
        }
        const count = buf.readUInt8(pos++);
        this.RegionData = [];
        for (let i = 0; i < count; i++) {
            const newObjRegionData = {
                RegionID: UUID_1.UUID.zero()
            };
            newObjRegionData['RegionID'] = new UUID_1.UUID(buf, pos);
            pos += 16;
            this.RegionData.push(newObjRegionData);
        }
        return pos - startPos;
    }
}
exports.RegionPresenceRequestByRegionIDMessage = RegionPresenceRequestByRegionIDMessage;
//# sourceMappingURL=RegionPresenceRequestByRegionID.js.map