"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegionPresenceResponseMessage = void 0;
const UUID_1 = require("../UUID");
const IPAddress_1 = require("../IPAddress");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class RegionPresenceResponseMessage {
    name = 'RegionPresenceResponse';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.Zerocoded | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.RegionPresenceResponse;
    RegionData;
    getSize() {
        return this.calculateVarVarSize(this.RegionData, 'Message', 1) + ((42) * this.RegionData.length) + 1;
    }
    calculateVarVarSize(block, paramName, extraPerVar) {
        let size = 0;
        for (const bl of block) {
            size += bl[paramName].length + extraPerVar;
        }
        return size;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        const count = this.RegionData.length;
        buf.writeUInt8(this.RegionData.length, pos++);
        for (let i = 0; i < count; i++) {
            this.RegionData[i]['RegionID'].writeToBuffer(buf, pos);
            pos += 16;
            buf.writeInt32LE(this.RegionData[i]['RegionHandle'].low, pos);
            pos += 4;
            buf.writeInt32LE(this.RegionData[i]['RegionHandle'].high, pos);
            pos += 4;
            this.RegionData[i]['InternalRegionIP'].writeToBuffer(buf, pos);
            pos += 4;
            this.RegionData[i]['ExternalRegionIP'].writeToBuffer(buf, pos);
            pos += 4;
            buf.writeUInt16LE(this.RegionData[i]['RegionPort'], pos);
            pos += 2;
            buf.writeDoubleLE(this.RegionData[i]['ValidUntil'], pos);
            pos += 8;
            buf.writeUInt8(this.RegionData[i]['Message'].length, pos++);
            this.RegionData[i]['Message'].copy(buf, pos);
            pos += this.RegionData[i]['Message'].length;
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        if (pos >= buf.length) {
            return pos - startPos;
        }
        const count = buf.readUInt8(pos++);
        this.RegionData = [];
        for (let i = 0; i < count; i++) {
            const newObjRegionData = {
                RegionID: UUID_1.UUID.zero(),
                RegionHandle: long_1.default.ZERO,
                InternalRegionIP: IPAddress_1.IPAddress.zero(),
                ExternalRegionIP: IPAddress_1.IPAddress.zero(),
                RegionPort: 0,
                ValidUntil: 0,
                Message: Buffer.allocUnsafe(0)
            };
            newObjRegionData['RegionID'] = new UUID_1.UUID(buf, pos);
            pos += 16;
            newObjRegionData['RegionHandle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
            pos += 8;
            newObjRegionData['InternalRegionIP'] = new IPAddress_1.IPAddress(buf, pos);
            pos += 4;
            newObjRegionData['ExternalRegionIP'] = new IPAddress_1.IPAddress(buf, pos);
            pos += 4;
            newObjRegionData['RegionPort'] = buf.readUInt16LE(pos);
            pos += 2;
            newObjRegionData['ValidUntil'] = buf.readDoubleLE(pos);
            pos += 8;
            varLength = buf.readUInt8(pos++);
            newObjRegionData['Message'] = buf.slice(pos, pos + varLength);
            pos += varLength;
            this.RegionData.push(newObjRegionData);
        }
        return pos - startPos;
    }
}
exports.RegionPresenceResponseMessage = RegionPresenceResponseMessage;
//# sourceMappingURL=RegionPresenceResponse.js.map