"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegionIDAndHandleReplyMessage = void 0;
const UUID_1 = require("../UUID");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class RegionIDAndHandleReplyMessage {
    name = 'RegionIDAndHandleReply';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.RegionIDAndHandleReply;
    ReplyBlock;
    getSize() {
        return 24;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.ReplyBlock['RegionID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeInt32LE(this.ReplyBlock['RegionHandle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.ReplyBlock['RegionHandle'].high, pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjReplyBlock = {
            RegionID: UUID_1.UUID.zero(),
            RegionHandle: long_1.default.ZERO
        };
        newObjReplyBlock['RegionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjReplyBlock['RegionHandle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        this.ReplyBlock = newObjReplyBlock;
        return pos - startPos;
    }
}
exports.RegionIDAndHandleReplyMessage = RegionIDAndHandleReplyMessage;
//# sourceMappingURL=RegionIDAndHandleReply.js.map