"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.RemoveAttachmentMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class RemoveAttachmentMessage {
    name = 'RemoveAttachment';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.RemoveAttachment;
    AgentData;
    AttachmentBlock;
    getSize() {
        return 49;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentData['SessionID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt8(this.AttachmentBlock['AttachmentPoint'], pos++);
        this.AttachmentBlock['ItemID'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjAgentData = {
            AgentID: UUID_1.UUID.zero(),
            SessionID: UUID_1.UUID.zero()
        };
        newObjAgentData['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAgentData['SessionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.AgentData = newObjAgentData;
        const newObjAttachmentBlock = {
            AttachmentPoint: 0,
            ItemID: UUID_1.UUID.zero()
        };
        newObjAttachmentBlock['AttachmentPoint'] = buf.readUInt8(pos++);
        newObjAttachmentBlock['ItemID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.AttachmentBlock = newObjAttachmentBlock;
        return pos - startPos;
    }
}
exports.RemoveAttachmentMessage = RemoveAttachmentMessage;
//# sourceMappingURL=RemoveAttachment.js.map