"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestTrustedCircuitMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class RequestTrustedCircuitMessage {
    name = 'RequestTrustedCircuit';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.RequestTrustedCircuit;
    getSize() {
        return 0;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        return 0;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        return 0;
    }
}
exports.RequestTrustedCircuitMessage = RequestTrustedCircuitMessage;
//# sourceMappingURL=RequestTrustedCircuit.js.map