"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SendXferPacketMessage = void 0;
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class SendXferPacketMessage {
    name = 'SendXferPacket';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyHigh;
    id = Message_1.Message.SendXferPacket;
    XferID;
    DataPacket;
    getSize() {
        return (this.DataPacket['Data'].length + 2) + 12;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeInt32LE(this.XferID['ID'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.XferID['ID'].high, pos);
        pos += 4;
        buf.writeUInt32LE(this.XferID['Packet'], pos);
        pos += 4;
        buf.writeUInt16LE(this.DataPacket['Data'].length, pos);
        pos += 2;
        this.DataPacket['Data'].copy(buf, pos);
        pos += this.DataPacket['Data'].length;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        const newObjXferID = {
            ID: long_1.default.ZERO,
            Packet: 0
        };
        newObjXferID['ID'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        newObjXferID['Packet'] = buf.readUInt32LE(pos);
        pos += 4;
        this.XferID = newObjXferID;
        const newObjDataPacket = {
            Data: Buffer.allocUnsafe(0)
        };
        varLength = buf.readUInt16LE(pos);
        pos += 2;
        newObjDataPacket['Data'] = buf.slice(pos, pos + varLength);
        pos += varLength;
        this.DataPacket = newObjDataPacket;
        return pos - startPos;
    }
}
exports.SendXferPacketMessage = SendXferPacketMessage;
//# sourceMappingURL=SendXferPacket.js.map