"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SetStartLocationMessage = void 0;
const UUID_1 = require("../UUID");
const Vector3_1 = require("../Vector3");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class SetStartLocationMessage {
    name = 'SetStartLocation';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.Zerocoded | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.SetStartLocation;
    StartLocationData;
    getSize() {
        return 68;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.StartLocationData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.StartLocationData['RegionID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt32LE(this.StartLocationData['LocationID'], pos);
        pos += 4;
        buf.writeInt32LE(this.StartLocationData['RegionHandle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.StartLocationData['RegionHandle'].high, pos);
        pos += 4;
        this.StartLocationData['LocationPos'].writeToBuffer(buf, pos, false);
        pos += 12;
        this.StartLocationData['LocationLookAt'].writeToBuffer(buf, pos, false);
        pos += 12;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjStartLocationData = {
            AgentID: UUID_1.UUID.zero(),
            RegionID: UUID_1.UUID.zero(),
            LocationID: 0,
            RegionHandle: long_1.default.ZERO,
            LocationPos: Vector3_1.Vector3.getZero(),
            LocationLookAt: Vector3_1.Vector3.getZero()
        };
        newObjStartLocationData['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjStartLocationData['RegionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjStartLocationData['LocationID'] = buf.readUInt32LE(pos);
        pos += 4;
        newObjStartLocationData['RegionHandle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        newObjStartLocationData['LocationPos'] = new Vector3_1.Vector3(buf, pos, false);
        pos += 12;
        newObjStartLocationData['LocationLookAt'] = new Vector3_1.Vector3(buf, pos, false);
        pos += 12;
        this.StartLocationData = newObjStartLocationData;
        return pos - startPos;
    }
}
exports.SetStartLocationMessage = SetStartLocationMessage;
//# sourceMappingURL=SetStartLocation.js.map