"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimulatorSetMapMessage = void 0;
const UUID_1 = require("../UUID");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class SimulatorSetMapMessage {
    name = 'SimulatorSetMap';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.SimulatorSetMap;
    MapData;
    getSize() {
        return 28;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeInt32LE(this.MapData['RegionHandle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.MapData['RegionHandle'].high, pos);
        pos += 4;
        buf.writeInt32LE(this.MapData['Type'], pos);
        pos += 4;
        this.MapData['MapImage'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjMapData = {
            RegionHandle: long_1.default.ZERO,
            Type: 0,
            MapImage: UUID_1.UUID.zero()
        };
        newObjMapData['RegionHandle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        newObjMapData['Type'] = buf.readInt32LE(pos);
        pos += 4;
        newObjMapData['MapImage'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.MapData = newObjMapData;
        return pos - startPos;
    }
}
exports.SimulatorSetMapMessage = SimulatorSetMapMessage;
//# sourceMappingURL=SimulatorSetMap.js.map