"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimulatorViewerTimeMessageMessage = void 0;
const Vector3_1 = require("../Vector3");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class SimulatorViewerTimeMessageMessage {
    name = 'SimulatorViewerTimeMessage';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.SimulatorViewerTimeMessage;
    TimeInfo;
    getSize() {
        return 44;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeInt32LE(this.TimeInfo['UsecSinceStart'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.TimeInfo['UsecSinceStart'].high, pos);
        pos += 4;
        buf.writeUInt32LE(this.TimeInfo['SecPerDay'], pos);
        pos += 4;
        buf.writeUInt32LE(this.TimeInfo['SecPerYear'], pos);
        pos += 4;
        this.TimeInfo['SunDirection'].writeToBuffer(buf, pos, false);
        pos += 12;
        buf.writeFloatLE(this.TimeInfo['SunPhase'], pos);
        pos += 4;
        this.TimeInfo['SunAngVelocity'].writeToBuffer(buf, pos, false);
        pos += 12;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjTimeInfo = {
            UsecSinceStart: long_1.default.ZERO,
            SecPerDay: 0,
            SecPerYear: 0,
            SunDirection: Vector3_1.Vector3.getZero(),
            SunPhase: 0,
            SunAngVelocity: Vector3_1.Vector3.getZero()
        };
        newObjTimeInfo['UsecSinceStart'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        newObjTimeInfo['SecPerDay'] = buf.readUInt32LE(pos);
        pos += 4;
        newObjTimeInfo['SecPerYear'] = buf.readUInt32LE(pos);
        pos += 4;
        newObjTimeInfo['SunDirection'] = new Vector3_1.Vector3(buf, pos, false);
        pos += 12;
        newObjTimeInfo['SunPhase'] = buf.readFloatLE(pos);
        pos += 4;
        newObjTimeInfo['SunAngVelocity'] = new Vector3_1.Vector3(buf, pos, false);
        pos += 12;
        this.TimeInfo = newObjTimeInfo;
        return pos - startPos;
    }
}
exports.SimulatorViewerTimeMessageMessage = SimulatorViewerTimeMessageMessage;
//# sourceMappingURL=SimulatorViewerTimeMessage.js.map