"use strict";
// This file has been automatically generated by writeMessageClasses.js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SoundTriggerMessage = void 0;
const UUID_1 = require("../UUID");
const Vector3_1 = require("../Vector3");
const long_1 = __importDefault(require("long"));
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class SoundTriggerMessage {
    name = 'SoundTrigger';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyHigh;
    id = Message_1.Message.SoundTrigger;
    SoundData;
    getSize() {
        return 88;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.SoundData['SoundID'].writeToBuffer(buf, pos);
        pos += 16;
        this.SoundData['OwnerID'].writeToBuffer(buf, pos);
        pos += 16;
        this.SoundData['ObjectID'].writeToBuffer(buf, pos);
        pos += 16;
        this.SoundData['ParentID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeInt32LE(this.SoundData['Handle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.SoundData['Handle'].high, pos);
        pos += 4;
        this.SoundData['Position'].writeToBuffer(buf, pos, false);
        pos += 12;
        buf.writeFloatLE(this.SoundData['Gain'], pos);
        pos += 4;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjSoundData = {
            SoundID: UUID_1.UUID.zero(),
            OwnerID: UUID_1.UUID.zero(),
            ObjectID: UUID_1.UUID.zero(),
            ParentID: UUID_1.UUID.zero(),
            Handle: long_1.default.ZERO,
            Position: Vector3_1.Vector3.getZero(),
            Gain: 0
        };
        newObjSoundData['SoundID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjSoundData['OwnerID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjSoundData['ObjectID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjSoundData['ParentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjSoundData['Handle'] = new long_1.default(buf.readInt32LE(pos), buf.readInt32LE(pos + 4));
        pos += 8;
        newObjSoundData['Position'] = new Vector3_1.Vector3(buf, pos, false);
        pos += 12;
        newObjSoundData['Gain'] = buf.readFloatLE(pos);
        pos += 4;
        this.SoundData = newObjSoundData;
        return pos - startPos;
    }
}
exports.SoundTriggerMessage = SoundTriggerMessage;
//# sourceMappingURL=SoundTrigger.js.map