"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscribeLoadMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class SubscribeLoadMessage {
    name = 'SubscribeLoad';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.SubscribeLoad;
    getSize() {
        return 0;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        return 0;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        return 0;
    }
}
exports.SubscribeLoadMessage = SubscribeLoadMessage;
//# sourceMappingURL=SubscribeLoad.js.map