"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.TestMessageMessage = void 0;
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class TestMessageMessage {
    name = 'TestMessage';
    messageFlags = MessageFlags_1.MessageFlags.Zerocoded | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.TestMessage;
    TestBlock1;
    NeighborBlock;
    getSize() {
        return 52;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        buf.writeUInt32LE(this.TestBlock1['Test1'], pos);
        pos += 4;
        const count = 4;
        for (let i = 0; i < count; i++) {
            buf.writeUInt32LE(this.NeighborBlock[i]['Test0'], pos);
            pos += 4;
            buf.writeUInt32LE(this.NeighborBlock[i]['Test1'], pos);
            pos += 4;
            buf.writeUInt32LE(this.NeighborBlock[i]['Test2'], pos);
            pos += 4;
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjTestBlock1 = {
            Test1: 0
        };
        newObjTestBlock1['Test1'] = buf.readUInt32LE(pos);
        pos += 4;
        this.TestBlock1 = newObjTestBlock1;
        const count = 4;
        this.NeighborBlock = [];
        for (let i = 0; i < count; i++) {
            const newObjNeighborBlock = {
                Test0: 0,
                Test1: 0,
                Test2: 0
            };
            newObjNeighborBlock['Test0'] = buf.readUInt32LE(pos);
            pos += 4;
            newObjNeighborBlock['Test1'] = buf.readUInt32LE(pos);
            pos += 4;
            newObjNeighborBlock['Test2'] = buf.readUInt32LE(pos);
            pos += 4;
            this.NeighborBlock.push(newObjNeighborBlock);
        }
        return pos - startPos;
    }
}
exports.TestMessageMessage = TestMessageMessage;
//# sourceMappingURL=TestMessage.js.map