"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferInventoryMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class TransferInventoryMessage {
    name = 'TransferInventory';
    messageFlags = MessageFlags_1.MessageFlags.Trusted | MessageFlags_1.MessageFlags.Zerocoded | MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.TransferInventory;
    InfoBlock;
    InventoryBlock;
    getSize() {
        return ((17) * this.InventoryBlock.length) + 49;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.InfoBlock['SourceID'].writeToBuffer(buf, pos);
        pos += 16;
        this.InfoBlock['DestID'].writeToBuffer(buf, pos);
        pos += 16;
        this.InfoBlock['TransactionID'].writeToBuffer(buf, pos);
        pos += 16;
        const count = this.InventoryBlock.length;
        buf.writeUInt8(this.InventoryBlock.length, pos++);
        for (let i = 0; i < count; i++) {
            this.InventoryBlock[i]['InventoryID'].writeToBuffer(buf, pos);
            pos += 16;
            buf.writeInt8(this.InventoryBlock[i]['Type'], pos++);
        }
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        const newObjInfoBlock = {
            SourceID: UUID_1.UUID.zero(),
            DestID: UUID_1.UUID.zero(),
            TransactionID: UUID_1.UUID.zero()
        };
        newObjInfoBlock['SourceID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjInfoBlock['DestID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjInfoBlock['TransactionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.InfoBlock = newObjInfoBlock;
        if (pos >= buf.length) {
            return pos - startPos;
        }
        const count = buf.readUInt8(pos++);
        this.InventoryBlock = [];
        for (let i = 0; i < count; i++) {
            const newObjInventoryBlock = {
                InventoryID: UUID_1.UUID.zero(),
                Type: 0
            };
            newObjInventoryBlock['InventoryID'] = new UUID_1.UUID(buf, pos);
            pos += 16;
            newObjInventoryBlock['Type'] = buf.readInt8(pos++);
            this.InventoryBlock.push(newObjInventoryBlock);
        }
        return pos - startPos;
    }
}
exports.TransferInventoryMessage = TransferInventoryMessage;
//# sourceMappingURL=TransferInventory.js.map