"use strict";
// This file has been automatically generated by writeMessageClasses.js
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateUserInfoMessage = void 0;
const UUID_1 = require("../UUID");
const MessageFlags_1 = require("../../enums/MessageFlags");
const Message_1 = require("../../enums/Message");
class UpdateUserInfoMessage {
    name = 'UpdateUserInfo';
    messageFlags = MessageFlags_1.MessageFlags.FrequencyLow;
    id = Message_1.Message.UpdateUserInfo;
    AgentData;
    UserData;
    getSize() {
        return (this.UserData['DirectoryVisibility'].length + 1) + 33;
    }
    // @ts-ignore
    writeToBuffer(buf, pos) {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentData['SessionID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt8((this.UserData['IMViaEMail']) ? 1 : 0, pos++);
        buf.writeUInt8(this.UserData['DirectoryVisibility'].length, pos++);
        this.UserData['DirectoryVisibility'].copy(buf, pos);
        pos += this.UserData['DirectoryVisibility'].length;
        return pos - startPos;
    }
    // @ts-ignore
    readFromBuffer(buf, pos) {
        const startPos = pos;
        let varLength = 0;
        const newObjAgentData = {
            AgentID: UUID_1.UUID.zero(),
            SessionID: UUID_1.UUID.zero()
        };
        newObjAgentData['AgentID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        newObjAgentData['SessionID'] = new UUID_1.UUID(buf, pos);
        pos += 16;
        this.AgentData = newObjAgentData;
        const newObjUserData = {
            IMViaEMail: false,
            DirectoryVisibility: Buffer.allocUnsafe(0)
        };
        newObjUserData['IMViaEMail'] = (buf.readUInt8(pos++) === 1);
        varLength = buf.readUInt8(pos++);
        newObjUserData['DirectoryVisibility'] = buf.slice(pos, pos + varLength);
        pos += varLength;
        this.UserData = newObjUserData;
        return pos - startPos;
    }
}
exports.UpdateUserInfoMessage = UpdateUserInfoMessage;
//# sourceMappingURL=UpdateUserInfo.js.map